/*
 * File: app/store/States.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SpendingPortal.store.States', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyStore1',
            data: [
                {
                    abbr: 'AK',
                    label: 'Alaska'
                },
                {
                    abbr: 'AL',
                    label: 'Alabama'
                },
                {
                    abbr: 'AR',
                    label: 'Arkansas'
                },
                {
                    abbr: 'AZ',
                    label: 'Arizona'
                },
                {
                    abbr: 'CA',
                    label: 'California'
                },
                {
                    abbr: 'CO',
                    label: 'Colorado'
                },
                {
                    abbr: 'CT',
                    label: 'Connecticut'
                },
                {
                    abbr: 'DC',
                    label: 'District of Columbia'
                },
                {
                    abbr: 'DE',
                    label: 'Delaware'
                },
                {
                    abbr: 'FL',
                    label: 'Florida'
                },
                {
                    abbr: 'GA',
                    label: 'Georgia'
                },
                {
                    abbr: 'HI',
                    label: 'Hawaii'
                },
                {
                    abbr: 'IA',
                    label: 'Iowa'
                },
                {
                    abbr: 'ID',
                    label: 'Idaho'
                },
                {
                    abbr: 'IL',
                    label: 'Illinois'
                },
                {
                    abbr: 'IN',
                    label: 'Indiana'
                },
                {
                    abbr: 'KS',
                    label: 'Kansas'
                },
                {
                    abbr: 'KY',
                    label: 'Kentucky'
                },
                {
                    abbr: 'LA',
                    label: 'Louisiana'
                },
                {
                    abbr: 'MA',
                    label: 'Massachusetts'
                },
                {
                    abbr: 'ME',
                    label: 'Maine'
                },
                {
                    abbr: 'MD',
                    label: 'Maryland'
                },
                {
                    abbr: 'MI',
                    label: 'Michigan'
                },
                {
                    abbr: 'MN',
                    label: 'Minnesota'
                },
                {
                    abbr: 'MS',
                    label: 'Mississippi'
                },
                {
                    abbr: 'MO',
                    label: 'Montana'
                },
                {
                    abbr: 'NC',
                    label: 'North Carolina'
                },
                {
                    abbr: 'ND',
                    label: 'North Dakota'
                },
                {
                    abbr: 'NE',
                    label: 'Nebraska'
                },
                {
                    abbr: 'NH',
                    label: 'New Hampshire'
                },
                {
                    abbr: 'NJ',
                    label: 'New Jersey'
                },
                {
                    abbr: 'NM',
                    label: 'New Mexico'
                },
                {
                    abbr: 'NV',
                    label: 'Nevada'
                },
                {
                    abbr: 'NY',
                    label: 'New York'
                },
                {
                    abbr: 'OH',
                    label: 'Ohio'
                },
                {
                    abbr: 'OK',
                    label: 'Oklahoma'
                },
                {
                    abbr: 'OR',
                    label: 'Oregon'
                },
                {
                    abbr: 'PA',
                    label: 'Pennsylvania'
                },
                {
                    abbr: 'RI',
                    label: 'Rhode Island'
                },
                {
                    abbr: 'SC',
                    label: 'South Carolina'
                },
                {
                    abbr: 'SD',
                    label: 'South Dakota'
                },
                {
                    abbr: 'TN',
                    label: 'Tennessee'
                },
                {
                    abbr: 'TX',
                    label: 'Texas'
                },
                {
                    abbr: 'UT',
                    label: 'Utah'
                },
                {
                    abbr: 'VT',
                    label: 'Vermont'
                },
                {
                    abbr: 'VA',
                    label: 'Virginia'
                },
                {
                    abbr: 'WA',
                    label: 'Washington'
                },
                {
                    abbr: 'WI',
                    label: 'Wisconsin'
                },
                {
                    abbr: 'WV',
                    label: 'West Virginia'
                },
                {
                    abbr: 'WY',
                    label: 'Wyoming'
                }
            ],
            pageSize: 600,
            fields: [
                {
                    name: 'abbr'
                },
                {
                    name: 'label'
                }
            ]
        }, cfg)]);
    }
});