/*
 * File: app/model/Earmark.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SpendingPortal.model.Earmark', {
    extend: 'Ext.data.Model',

    fields: [{
        name: 'EARMARK_ID'
    }, {
        name: 'EARMARK_DESCRIPTION'
    }, {
        name: 'ENACTED_YEAR',
        type: 'int'
    }, {
        name: 'AGENCY_TITLE'
    }, {
        name: 'BUREAU_TITLE'
    }, {
        name: 'AMT_CONF',
        type: 'float'
    }, {
        name: 'SPONSOR'
    }, {
        name: 'SPENDINGCOMMITTEE'
    }, {
        convert: function(v, rec) {
            console.log(v,rec);
            if (rec.data.SPONSOR) {
                return rec.get('SPONSOR').LASTNAME + ", " + rec.get('SPONSOR').FIRSTNAME;
            } else {
                return v;
            }
        },
        name: 'SPONSORNAME'
    }],

    proxy: {
        type: 'jsonp',
        url: 'http://www.senchatraining.com/ftextjs4/webservices/earmark.cfc?method=wsBigJSONP',
        reader: {
            type: 'json',
            root: 'ROWS',
            successProperty: 'SUCCESS',
            totalProperty: 'RESULTS'
        }
    }
});