/*
 * File: app/model/Sponsor.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SpendingPortal.model.Sponsor', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'IDSPONSOR'
        },
        {
            name: 'HONORIFIC'
        },
        {
            name: 'FIRSTNAME'
        },
        {
            name: 'LASTNAME'
        },
        {
            name: 'PARTY'
        },
        {
            name: 'STATE'
        }
    ],

    proxy: {
        type: 'jsonp',
        url: 'http://www.senchatraining.com/ftextjs4/webservices/sponsor.cfc?method=wsBigJSONP',
        reader: {
            type: 'json',
            root: 'ROWS',
            successProperty: 'SUCCESS',
            totalProperty: 'RESULTS'
        }
    }
});