/*
 * File: app/view/Sponsors.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SpendingPortal.view.Sponsors', {
    extend: 'Ext.window.Window',
    alias: 'widget.sponsors',

    requires: [
        'Ext.grid.Panel',
        'Ext.selection.RowModel',
        'Ext.form.field.ComboBox'
    ],

    autoShow: true,
    height: 600,
    width: 472,
    constrain: true,
    layout: {
        type: 'fit'
    },
    closable: false,
    title: 'Congressional Representatives',
    maximizable: true,
    minimizable: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    itemId: 'sponsorsgrid',
                    collapseFirst: false,
                    frameHeader: false,
                    header: false,
                    columnLines: true,
                    store: 'Sponsors',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return value.substring(0,3) + '.';
                            },
                            width: 50,
                            dataIndex: 'HONORIFIC',
                            text: 'Hon'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'FIRSTNAME',
                            text: 'First Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'LASTNAME',
                            text: 'Last Name',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'PARTY',
                            text: 'Party'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 58,
                            dataIndex: 'STATE',
                            text: 'State'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'combobox',
                                    tpl: '<tpl for="."><div class="x-boundlist-item">{abbr} - {label}</div></tpl>',
                                    flex: 1,
                                    itemId: 'stateFilter',
                                    fieldLabel: 'Filter by State:',
                                    displayField: 'label',
                                    forceSelection: true,
                                    multiSelect: true,
                                    queryMode: 'local',
                                    store: 'States',
                                    valueField: 'abbr'
                                }
                            ]
                        }
                    ],
                    selModel: Ext.create('Ext.selection.RowModel', {
                        mode: 'MULTI'
                    })
                }
            ]
        });

        me.callParent(arguments);
    }

});