/*
 * File: app/store/BookChapters.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SpendingPortal.store.BookChapters', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyStore4',
            data: [
                {
                    id: '1',
                    label: 'Chapter 1: Introduction'
                },
                {
                    id: '2',
                    label: 'Chapter 2: Developing Mobile Apps with Sencha Touch'
                },
                {
                    id: '3',
                    label: 'Chapter 3: Developing Desktop Apps with Ext JS 4'
                },
                {
                    id: '4',
                    label: 'Chapter 4: Theming Your Apps'
                },
                {
                    id: '5',
                    label: 'Chapter 5: Deploying Your Apps'
                }
            ],
            pageSize: 600,
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'label'
                }
            ]
        }, cfg)]);
    }
});